### PR TITLE
Sync with Wynyard's version of PowerUp.

### PR DESCRIPTION
**Pull request by WynyardEngineering**
@llevera: please review - this is everything Wynyard has added/changed in the last 18 months or so.

### CODE REVIEW

**Comment by llevera** [comment]
Can you just quickly explain in words where most of the changes have occurred. A quick glance suggests there are quite a few changes, but actually comparatively innocuous

**Comment by WynyardEngineering** [comment]
Good point.

In the Powershell extensions:  new cmdlets for zip file manipulation; better settings handling (no longer have to be tab-delimited); added support for "PowerUp remote agent" which I'll open-source in the near future.

In the Powershell modules: all write-host statements switched to write-output - helps with capturing logs (see changes to deploy.bat to capture logs); removed quite a few unlicensed exes - these are often installed as part of Windows anyway; settings substitution can now do "sub-files" which helps when doing things like WCF configuration.

On the build side: removed nunit - better to just install nunit.runners nuget package and use that.

There are now 3 nuspecs, meaning it's possible to release PowerUp in 3 forms: "normal" (i.e. everything, as presently), "deploy-only" (just the deploy bits), and "build-only" (just the build bits);

**Comment by WynyardEngineering** [comment]
Incidentally, we removed all Umbraco support (it's stale, and not needed) here at Wynyard.  I assumed you wanted to keep it in this version...?

**Comment by paulsuart** [comment]
Just seen this.... thanks!

**Pull request merged**
